### ISSUE TITLE
Add life cycle for visualization

### ISSUE THREAD

**Issue by xwavex** [corlab/gazebo-trajectory-visualization-plugin#3]
It should be possible to set a life cycle to the points in a trajectory visualization so that very old points automatically get deleted...
Or that a trajectory can have a fixed size n (that can be set through some operations etc...) and for each new point > n the oldest point gets deleted...
Something like that.

**Comment by arognar** [comment]
Added activateLifecycle,deactivateLifecycle and setLifecycle . Default is 3000 Points .
